[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[window]
opacity = 0.95
decorations = "none"
padding = { x = 6, y = 6 }
dynamic_padding = true

[general]
import = ["~/.config/alacritty/themes/themes/github_dark.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0
