[font]
size=12

[font.normal]
family="JetBrainsMonoNerdFont"
style="Regular"

[window]
opacity = 0.95
decorations = "none"
padding = { x = 6, y = 6 }
dynamic_padding = true

[general]
import = ["~/.config/alacritty/themes/themes/github_dark_default.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0

