# onedark vibe (przybliÅ¼one kolory)
[palettes.onedark]
fg = "#abb2bf"
bg = "#1e222a"
blue = "#61afef"
green = "#98c379"
purple = "#c678dd"
red = "#e06c75"
yellow = "#e5c07b"
cyan = "#56b6c2"

# uÅ¼ywamy tej palety
palette = "onedark"

# ogÃ³lny format: katalog, git, python, znak zachÄ™ty
format = """
($directory)
($git_branch$git_status)($python)
$character
"""

[directory]
truncate_to_repo = false
truncation_length = 0

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 10
truncation_symbol = 'â€¦'
ignore_branches = []

[git_commit]
commit_hash_length = 6
tag_symbol = 'ğŸ”– '

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[python]
pyenv_version_name = true
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[character]
success_symbol = "[âœ](fg:green) "
error_symbol = "[âœ](fg:red) "

# wywalanie Å›mieci, ktÃ³rych nie chcesz
[hostname]
disabled = true
[time]
disabled = true
[username]
disabled = false
